### ISSUE TITLE
The CSS file this plugin hot-links to 404s

### ISSUE THREAD

**Issue by barrymcgee** [weirdpattern/gatsby-remark-embed-gist#11]
All my embed scripts are now unstyled as this link 404s:

https://assets-cdn.github.com/assets/gist-embed-87673c31a5b37b5e6556b63e1081ebbc.css

Could you please update your plugin to use local styles?

**Comment by barrymcgee** [comment]
<img width="1241" alt="Screenshot 2019-03-11 at 14 10 58" src="https://user-images.githubusercontent.com/505570/54130023-864a8000-4407-11e9-999b-ba2a6659a4ff.png">

**Comment by weirdpattern** [comment]
Hi @barrymcgee, please take a look at #8 
This was fixed a few days ago and I'm looking for better ways to handle this type of scenarios.
For now, please update to the latest version of the plugin and rebuild your site.

**Comment by weirdpattern** [comment]
Also, local styles are already supported.
You can tell the plugin not to load the default css file and provide your own via your layour.

```json
{
  resolve: "gatsby-transformer-remark",
  options: {
    plugins: [
      {
        resolve: "gatsby-remark-embed-gist",
        options: {
          // a flag indicating whether the github default gist css should be included or not
          // default: true
          includeDefaultCss: true,

          ...
        }
      }
    ]
  }
}
````

**Comment by weirdpattern** [comment]
Closing this issues as I'm already tracking this in #10

**Comment by barrymcgee** [comment]
@weirdpattern Thank you for your quick response 🙏🏻

**Comment by weirdpattern** [comment]
@barrymcgee no probs, don't hesitate in creating a new bug if you find something else or have a suggestion for the plug-in...
