### ISSUE TITLE
1.1.8 does not appear to work

### ISSUE THREAD

**Issue by alexkirsz** [weirdpattern/gatsby-remark-embed-gist#18]
I tried updating to 1.1.8, but my gists simply show up as code elements. Rolling back to 1.1.7 fixes the issue.

For reference, I'm writing the following:

```
`gist:alexkirsz/011ade925d7cd9a82c5e49b2a53bbc3c`
```

**Comment by weirdpattern** [comment]
I think I know what's going on.
I will try and get this fixed today.

Sorry about that!

**Comment by weirdpattern** [comment]
This should be fixed now... sorry for the trouble
