### ISSUE TITLE
Highlighting breaks with camelCased file names

### ISSUE THREAD

**Issue by tyhopp** [weirdpattern/gatsby-remark-embed-gist#2]
Hi @weirdpattern, love your plugin, been using it a lot [on my site lately](https://tyhopp.com).

It looks like the line highlighting breaks with file names that contain capitals, because the id applied to lines becomes all lowercase.

I'll submit a PR with a proposed fix 👌

**Comment by weirdpattern** [comment]
Hi @tyhopp thanks for the contribution.
I'm glad this plugin is being used by someone other than me 👍

**Comment by tyhopp** [comment]
And thank you, your plugin is awesome! Also we're definitely not the only ones, the Gatsby site says there's 900+ downloads of it 😄

**Comment by weirdpattern** [comment]
Merged and publishing as v1.1.4
