### ISSUE TITLE
Hitting GitHub’s ratelimit during build

### ISSUE THREAD

**Issue by necccc** [weirdpattern/gatsby-remark-embed-gist#21]
Hi,
my builds failed recently, and found out its because the gist requests return an error, telling me that apparently I’ve hit a ratelimit.

Tried to work around in a forked repo, this is what I’ve got:

Adding a personal access token does not have an effect, since the gist url this plugin calls is not a GH api url :( 

Using the gist API with access token works, but that gives us unformatted raw data of gist content. Can’t find a lib that creates formatted gist embed output from the raw data, that would help.

Have anyone seen this issue before?

**Comment by weirdpattern** [comment]
I haven't seen this issue before, how many gists are you loading?

As you said, the API will only give you the raw gist, which kind of defeats the whole purpose of the plugin... I will keep my eye open just in case...

**Comment by weirdpattern** [comment]
@necccc is this still an issue for you?

**Comment by weirdpattern** [comment]
not getting any answers, so closing this issue for now
