### ISSUE TITLE
CSS not loading when trying to embed gist

### ISSUE THREAD

**Issue by terror** [weirdpattern/gatsby-remark-embed-gist#30]
Hello, I am trying to embed a gist into my markdown and the CSS doesn't seem to be loading properly. Here is the result and my config.

## Result

![Screen Shot 2020-06-27 at 3 48 07 PM](https://user-images.githubusercontent.com/31192478/85930855-a8cb0b80-b88d-11ea-881d-caca823e0f08.png)

![Screen Shot 2020-06-27 at 3 45 44 PM](https://user-images.githubusercontent.com/31192478/85930832-77ead680-b88d-11ea-967a-63addc0ffc9c.png)

## Config
![Screen Shot 2020-06-27 at 3 46 04 PM](https://user-images.githubusercontent.com/31192478/85930837-833e0200-b88d-11ea-8fbc-e3df51963466.png)

Am I missing something here?

**Comment by weirdpattern** [comment]
Hi @terror what version of the plug-in are you using?
If this is the latest, can you try the previous version?

**Comment by terror** [comment]
> Hi @terror what version of the plug-in are you using?
> If this is the latest, can you try the previous version?

using version 1.1.10 (latest), I'll try using previous

**Comment by weirdpattern** [comment]
Cool, let me know... I merged a couple of PR a few days ago, so that might be it. In any case I will work on a fix tonight... 

Sorry for the inconvenience

**Comment by terror** [comment]
> Cool, let me know... I merged a couple of PR a few days ago, so that might be it. In any case I will work on a fix tonight...
> 
> Sorry for the inconvenience

It's all good, just downgraded to 1.1.9 and it seems to be working fine now!

**Comment by weirdpattern** [comment]
If you don't mind, I want to keep this open.
1.1.10 should work with the same configuration.

I will take a look tonight.

**Comment by terror** [comment]
> If you don't mind, I want to keep this open.
> 1.1.10 should work with the same configuration.
> 
> I will take a look tonight.

No problem, accidentally clicked close and comment

**Comment by weirdpattern** [comment]
Fixed in #31

**Comment by weirdpattern** [comment]
Alright, this should be working now.
