### ISSUE TITLE
Highlights and lines fail on files with a . prefix

### ISSUE THREAD

**Issue by myedibleenso** [weirdpattern/gatsby-remark-embed-gist#35]
Thank you for the great plugin, @weirdpattern !  I'm using v1.2.0 with MDX and am running into issues rendering highlights and specific lines for files with a `.` prefex (ex. `.travis.yml`, `.vimrc`, etc.).  Files without a leading `.` in their name render as expected.  

Here's an example:

`gist:tpope/1203867/.inputrc?highlights=7`

...which should map to https://gist.github.com/tpope/1203867#file-inputrc-L7

In such cases, `highlighted` isn't appended as a class:

- https://github.com/weirdpattern/gatsby-remark-embed-gist/blob/8246532490bb4b9d6f7ba61eab3e5c2fa6de8d78/src/index.js#L179

Specifying `lines=` for such files also seems to have no effect.  All lines end up getting displayed.

I'm not really sure what's going on here, as the file _is_ found and the regex you have defined replaces the leading `.` with `-` (`.travis.yml` -> `-travis-yml`). 

🤔 

Any ideas?

**Comment by weirdpattern** [comment]
Hi @myedibleenso I promise I will look into this as soon as I find the time. 
I've been playing catch up at work for a few weeks, but I think things are settling down now (I work in healthcare and I live in Texas, so pretty sure you get the idea 😷)

**Comment by myedibleenso** [comment]
Thanks, @weirdpattern , but please don't rush on my account.  Stay safe out there!

**Comment by weirdpattern** [comment]
Closed by #38, going to release in a few moments.
