### ISSUE TITLE
Highlighting regex is not global

### ISSUE THREAD

**Issue by tyhopp** [weirdpattern/gatsby-remark-embed-gist#4]
Also found that the regex [here](https://github.com/weirdpattern/gatsby-remark-embed-gist/blob/f21b93c575f0080a07e21978aee05db3d082047e/src/index.js#L132) wasn't changing a file name such as file.js to file-js for line highlighting.

**Comment by weirdpattern** [comment]
Ah! dunno how I missed this. Thanks!

**Comment by weirdpattern** [comment]
Merged and publishing as v1.1.4
