### ISSUE TITLE
Errors related to missing `key` prop

### ISSUE THREAD

**Issue by tdharmon** [weirdpattern/gatsby-remark-embed-gist#5]
While using this plugin, I encountered an error while in the build process:

```
Warning: Each child in an array or iterator should have a unique "key" prop.

Check the top-level render call using <head>. See https://fb.me/react-warning-keys for more information.
    in link
    in HTML
```

My guess is that there isn't a `key` prop while a gist is converted from blog of code to lines of code (my guess is that there needs to be a `key` prop per line of code). But I don't actually know what the issue is.

I'm on 1.1.4 of this plugin and Gatsby v2.0.35.

**Comment by weirdpattern** [comment]
Hey @tdharmon thanks for reporting this issue... funny thing, I noticed this too in my environment it just never occurred to me it was this plugin... anyway... looking into it now...

**Comment by weirdpattern** [comment]
Turns out the setHeadComponents receives an array of react components.
As with any other array, it is expected to contain a key property...
